# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#


production:
  api_key: "932983599627195"
  api_secret: "MARiIoYTNhQD0-LvgFcnrxwbwcY"


HTTP_AUTH_NAME: "butrfly"
HTTP_AUTH_PASSWORD: "butrfly"


CLOUDINARY_URL: "cloudinary://932983599627195:MARiIoYTNhQD0-LvgFcnrxwbwcY@butrfly"
